### PR TITLE
MSFT_Disk: Implement workaround for maximum size discrepancy (fixes #181)

### LINKED ISSUE #123: xDisk: Allow formatting ReFS without integrity features
**Details of the scenario you tried and the problem that is occurring:**
Disk containing databases for Exchange 2016 is supported using disk with ReFS, but the recommendation is to have integrity features turned off.
Currently this resource does not support this. I suggest adding a `[System.Boolean]` parameter `IntegrityStreams`. If the new parameter is left out or set to `$true`, the disk is formatted with integrity features turned on (default behavior today). If the new parameter is set to `$false` then the disk is formatted with integrity features turned off (new behavior).

>Best practice: Data integrity features must be disabled for the Exchange database (.edb) files or the volume that hosts these files. Integrity features can be enabled for volumes containing the content index catalog, provided that the volume does not contain any databases or log files.
>https://technet.microsoft.com/en-us/library/ee832792(v=exchg.160).aspx

Example formatting a disk with integrity features turned off.
```
$partition = Get-Disk -Number 1 | New-Partition -UseMaximumSize
$partition | Format-Volume -FileSystem 'ReFS' -SetIntegrityStreams:$false -NewFileSystemLabel 'ExData'
```

**The DSC configuration that is using the resource (as detailed as possible):**
```
xDisk SVolume
{
    DiskId = 1
    DriveLetter = 'E'
    FSFormat = 'ReFS'
    AllocationUnitSize = 64KB

    # New parameter proposal
    IntegrityStreams = $true
}
```
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### LINKED ISSUE #181: Azure VM Data Disk Max Partition Size is Different to Actual Size
#### Details of the scenario you tried and the problem that is occurring

Using Disk resource to create a partition on an empty data disk using all free space reports that the size of the partition is smaller than it maximum size:
![image](https://user-images.githubusercontent.com/7589164/49325544-52aabf00-f5a9-11e8-91a4-27eb75e0e720.png)

I was using a 1023 GB data disk, so it is possible that this is a behavior with specific disk sizes.

#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer bmddsctest with user sid S-1-5-21-393396716-4191445587-4237219874-500.
VERBOSE: [bmddsctest]: LCM:  [ Start  Set      ]
VERBOSE: [bmddsctest]: LCM:  [ Start  Resource ]  [[WaitForDisk]Disk2]
VERBOSE: [bmddsctest]: LCM:  [ Start  Test     ]  [[WaitForDisk]Disk2]
VERBOSE: [bmddsctest]:                            [[WaitForDisk]Disk2] Test-TargetResource: Checking for disk with Number '2'.
VERBOSE: [bmddsctest]:                            [[WaitForDisk]Disk2] Test-TargetResource: Found disk with Number '2' named 'Msft Virtual Disk'.
VERBOSE: [bmddsctest]: LCM:  [ End    Test     ]  [[WaitForDisk]Disk2]  in 2.0780 seconds.
VERBOSE: [bmddsctest]: LCM:  [ Skip   Set      ]  [[WaitForDisk]Disk2]
VERBOSE: [bmddsctest]: LCM:  [ End    Resource ]  [[WaitForDisk]Disk2]
VERBOSE: [bmddsctest]: LCM:  [ Start  Resource ]  [[Disk]EVolume]
VERBOSE: [bmddsctest]: LCM:  [ Start  Test     ]  [[Disk]EVolume]
VERBOSE: [bmddsctest]:                            [[Disk]EVolume] Test-TargetResource: Testing disk with Number '2' status for drive letter 'F'.
VERBOSE: [bmddsctest]:                            [[Disk]EVolume] Test-TargetResource: Checking if disk with Number '2' is initialized.
VERBOSE: [bmddsctest]:                            [[Disk]EVolume] Test-TargetResource: Partition assigned to drive F has size 1098301571072, which does not match expected size 1098302602752. Set AllowDestructive to $true to enable resizing of partition.
VERBOSE: [bmddsctest]:                            [[Disk]EVolume] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT BlockSize from Win32_Volume WHERE DriveLetter = 'F:','queryDialect' = WQL,'namespaceName' = root\c
imv2'.
VERBOSE: [bmddsctest]:                            [[Disk]EVolume] Operation 'Query CimInstances' complete.
VERBOSE: [bmddsctest]: LCM:  [ End    Test     ]  [[Disk]EVolume]  in 2.3230 seconds.
VERBOSE: [bmddsctest]: LCM:  [ Skip   Set      ]  [[Disk]EVolume]
VERBOSE: [bmddsctest]: LCM:  [ End    Resource ]  [[Disk]EVolume]
VERBOSE: [bmddsctest]: LCM:  [ End    Set      ]
VERBOSE: [bmddsctest]: LCM:  [ End    Set      ]    in  9.0260 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 9.149 seconds
```

The problem can be replicated outside of DSC, so is not specifically caused by the Disk resource but the behavior of `Get-PartitionSupportedSize`, `New-Partition -UseMaximumSize` and `Get-Partition`.

For example:
```powershell
$null = Clear-Disk -Number 2 -RemoveData -Confirm:$false
$null = Initialize-Disk -Number 2 -PartitionStyle GPT
$partition = New-Partition -DiskNumber 2 -UseMaximumSize

('Actual Partition Size: {0}' -f (Get-Partition -DiskNumber 2 -PartitionNumber 2).Size)
('Supported Partition Size: {0}' -f (Get-PartitionSupportedSize -DiskNumber 2 -PartitionNumber ($partition.PartitionNumber)).SizeMax)
```

#### Suggested solution to the issue


#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Storage
{
    Import-DSCResource -ModuleName StorageDsc

    Node localhost
    {
        WaitForDisk Disk2
        {
             DiskId = 2
             RetryIntervalSec = 60
             RetryCount = 60
        }

        Disk EVolume
        {
             DiskId = 2
             DriveLetter = 'F'
             DependsOn = '[WaitForDisk]Disk2'
        }
    }
}

Install-Module StorageDsc
Storage -OutputPath . -Verbose
Start-DscConfiguration -Wait -Force -Path .\Storage -ComputerName Localhost -Verbose
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.14393.2608                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.14393.2608                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1  
```
#### Version of the DSC module that was used ('dev' if using current dev branch)
4.3.0.0

### PR DESCRIPTION
**Pull request by nyanhp**
#### Pull Request (PR) description

This PR introduces a workaround that fixes issue #181 where the reported maximum supported size of a partition would be approximately 1MB bigger than the actual size of the partition. As long as it is unclear why the New-Partition and Get-PartitionSupportedSize cmdlets report different data if neither Offset nor Alignment parameters are used, this workaround should remain in place.

If this is not the case, Test-TargetResource for a disk configured to use the remaining size will always return false and trigger an endless cycle of LCM runs.

#### This Pull Request (PR) fixes the following issues

- Fixes #181

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/197)

### CODE REVIEW

**Comment by nyanhp** [comment]
I have 0 ideas why the build suddenly fails. I did a rebase since the changelog was getting in the way of a merge. Will have a look

**Comment by PlagueHO** [comment]
Thanks @nyanhp - I'll get onto this review this weekend (finally will have some free time).

**Comment by PlagueHO** [comment]
Hi @nyanhp - are you still working on this one?

**Comment by PlagueHO** [comment]
Closing because replaced by #213

**Pull request closed without merging**
