### PR TITLE
Revert "Disk: correct volume error -  drive is read only"

### PR DESCRIPTION
**Pull request by PlagueHO**
I messed up and didn't notice that this PR was made to master branch. So I need to revert it. @johlju - can you review the revert for me?

@JoshuaJSwain - sorry, I didn't notice you'd submitted your PR against master. So I'll need to revert it. Can you please re-raise it against Dev branch for me and I'll get it through.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/189)

### CODE REVIEW

**Comment by PlagueHO** [comment]
P.S. We don't want to change anything at all here because this is a pure revert :)

**Comment by JoshuaJSwain** [comment]
> I messed up and didn't notice that this PR was made to master branch. So I need to revert it. @johlju - can you review the revert for me?
> 
> @JoshuaJSwain - sorry, I didn't notice you'd submitted your PR against master. So I'll need to revert it. Can you please re-raise it against Dev branch for me and I'll get it through.
> 
> This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/189)

Sorry for my goof, new PR https://github.com/PowerShell/StorageDsc/pull/190

**Comment by johlju** [comment]
Having an offline discussion about this with @PlagueHO

**Comment by johlju** [comment]
Looking into if we can just do interactive rebase `git rebase -i origin/master` and remove the commit, and the force push the master branch.

@PlagueHO What do you think?

**Comment by PlagueHO** [comment]
Thanks @johlju - I've e-mailed @kwirkykat to see what would be best for her. Mainly just want to make sure the release day all smooth! :grin: So I'll hold this open till I hear from her.

**Comment by PlagueHO** [comment]
Ps: no worries @JoshuaJSwain - we have all done it :grin: well I know I have.

**Comment by PlagueHO** [comment]
Woop! No need for this @kwirkykat fixed it for us :grin:

**Comment by johlju** [comment]
Awesome! Thanks @kwirkykat!

**Pull request closed without merging**
