### PR TITLE
Disk-AccessPath: fixing get-partition to pull current state of object

### LINKED ISSUE #145: xDiskAccessPath: Mounted disks get drive letter on reboot
**Details of the scenario you tried and the problem that is occurring:**

We are currently using the xStorage 3.4.0.0 module with the xDiskAccessPath resource within Chef to mount disks to a folder path. This works fine however on reboot the mounted disks are also assigned drive letters. Looking at native PowerShell there is an option like `Set-Partition -NoDefaultDriveLetter $true` and I was wondering if there is an option to ensure no drive letters are assigned when using DSC.

**The DSC configuration that is using the resource (as detailed as possible):**
```
dsc_resource 'd_data' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '2'
  property :accesspath, 'D:\Data'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
  property :FSLabel, 'Data'
end

dsc_resource 'd_system' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '3'
  property :accesspath, 'D:\System'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
  property :FSLabel, 'System'
end

dsc_resource 'd_logs' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '4'
  property :accesspath, 'D:\Logs'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
end
```
**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2012 R2
PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

```
3.4.0.0
```

### PR DESCRIPTION
**Pull request by JoshuaJSwain**
#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/198)

### CODE REVIEW

**Comment by JoshuaJSwain** [comment]
Updated with the patch. I want to run this through some integration tests before calling it good.

**Comment by JoshuaJSwain** [comment]
> Updated with the patch. I want to run this through some integration tests before calling it good.

I've tested this in a live environment and confirmed this fix.

**Comment by PlagueHO** [comment]
@JoshuaJSwain - when this one https://github.com/PowerShell/StorageDsc/pull/201 goes through then you can rebase and see if your tests still pass (I'd expect some to fail).

**Comment by PlagueHO** [comment]
Ok @JoshuaJSwain - #201 has gone through. Can you rebase and see if your tests pass and correct if necessary?

**Comment by PlagueHO** [comment]
Hi @JoshuaJSwain - this is what I expected- the tests to fail as they weren't actually very good. Now they are better tests you will need to correct them to validate your code correctly.

**Comment by JoshuaJSwain** [comment]
I take a look at this one week of 4/8. Should be straight forward to fix
them up. Thanks!

Josh Swain

**Pull request merged**
