### PR TITLE
Clean up Module Manifest - Fixes #191

### LINKED ISSUE #191: Clean up Module Manifest
The module manifest doesn't match standards.

The Author and Copyright needs to be updated. It should be autoformatted.

### LINKED ISSUE #192: Add DscResourcesToExport to Manifest and Remove Wildcards
To improve the information in the PowerShellGallery, add DscResourcesToExport to the module manifest.

Also remove wildcards from FunctionsToExport, CmdletsToExport, VariablesToExport, AliasesToExport.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR corrects the module manifest to adopt DSC Resource kit standards for Copyright, Author and Company.

Added 'DscResourcesToExport' to manifest to improve information in
  PowerShell Gallery and removed wildcards from 'FunctionsToExport',
  'CmdletsToExport', 'VariablesToExport' and 'AliasesToExport

#### This Pull Request (PR) fixes the following issues

- Fixes #191 
- Fixes #192

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing for me when you have a chance - just a simple Manifest cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/193)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I've rebased this one now. @johlju - would you mind reviewing when you have a change?

**Comment by johlju** [comment]
Okay, seems there are no real difference between the two when one is not a collaborator on a repo, it's not possible to "block" without being a collaborator. Hoping this is a change GitHub resolves eventually. 😄

**Comment by johlju** [comment]
Adding DscResourcesToExport, I’m curious what it actually improves in the PowerShell Gallery? If I look at SqlServer it do list the resources and that repo does not have the DscResourcesToExport. :thinking:
Just want to make sure we don’t add something that makes it harder to maintain when adding new resources. 
I was looking at adding this to SqlServerDsc as well if it added a better experience in the gallery, but can’t see that it does.

**Comment by PlagueHO** [comment]
@johlju - you know what: I assumed it did add these to the PS Gallery, but it appears that this happens anyway! So it must be just for Class based resources. The only thing it does is ensure it appears in the ExportedDscResources property of the modules object when scanning all modules:
image

But this isn't that important because if you want to find a list of DSC resources on the machine then using Get-DscResources is better.

The main reason for this though is that all the other modules I maintain are set up like this :grin: But happy to remove it if you think it isn't adding anything.

**Comment by johlju** [comment]
@PlagueHO Please keep it, no need to remove it. But then it is nothing we need to enforce for all modules at least, it can be up to the maintainer. Also, if it is missed when adding a new resource it's not a big deal (it does not break the resource).

**Comment by johlju** [comment]
@PlagueHO If you resolve the release notes I will LGTM this one. 😄

**Comment by PlagueHO** [comment]
Ah yes! Good catch @johlju - fixed now.

**Pull request merged**
