### PR TITLE
xAccessPath: Access Path not found - Fixes #121

### LINKED ISSUE #121: xDiskAccessPath fails test for disk and accesspath after disk format and folder creation.
**xDiskAccessPath:**
xDiskAccessPath fails the disk and access path test when the Disk and Folder are created within the same configuration.
```

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager
,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer TESTAPI with user sid S-1-5-21-1463861888-1148693830-2432142812-152739.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Testing disk with Number '1' status for drive letter 'E'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Checking if disk with Number '1' is initialized.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Disk with Number '1' is initialized with 'RAW' partition style. GPT required
.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[xDisk]Disk1]  in 2.3400 seconds.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Setting disk with Number '1' status for drive letter 'E'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Checking disk with Number '1' partition style.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Initializing disk with Number '1'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Disk with Number '1' does not contain a partition assigned to drive letter 'E
'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Creating partition on disk with Number '1' with drive letter 'E' using all fr
ee space.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Formatting the volume as 'NTFS'.
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]  [[xDisk]Disk1]  in 3.6750 seconds.
VERBOSE: [TESTAPI]: LCM:  [ End    Resource ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The system cannot find the file specified.
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The related file/directory is: E:\DATA.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[File]createDataFolder]  in 0.0320 seconds.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The system cannot find the file specified.
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The related file/directory is: E:\DATA.
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]  [[File]createDataFolder]  in 0.0150 seconds.
VERBOSE: [TESTAPI]: LCM:  [ End    Resource ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[xDiskAccessPath]dataAccessPath]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[xDiskAccessPath]dataAccessPath]
VERBOSE: [TESTAPI]:                            [[xDiskAccessPath]dataAccessPath] Test-TargetResource: Testing disk with Number '2' status for access path 'E:\D
ATA\'.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[xDiskAccessPath]dataAccessPath]  in 0.1250 seconds.
PowerShell DSC resource MSFT_xDiskAccessPath  failed to execute Test-TargetResource functionality with error message: Access Path 'E:\DATA\' is not found.
Parameter name: AccessPath 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : TestAPI
 
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : TestAPI
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 6.399 seconds


```**The DSC configuration that is using the resource (as detailed as possible):**
```
  Configuration AccessPath
  {
  
      Import-DscResource -ModuleName "xStorage"

  Node 'TestAPI' {
        
            xDisk Disk1{
              DiskID = "1"
              DriveLetter = 'E'
              FSLabel = "TestAPI_E"
              FSFormat="NTFS"
              }

              File createDataFolder{
              Type = 'Directory'
              DestinationPath = "E:\DATA\"
              Ensure = 'Present'
              DependsOn = "[xDisk]Disk1"
              }
             xDiskAccessPath dataAccessPath{
              DiskID=2
              AccessPath="E:\DATA\"
              Size = 5GB
              FSLabel = "E_DATA"
              FSFormat = 'NTFS'
              }
    }
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Microsoft Windows Server 2016 Standard
```
Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.1.14393.1480                                                                                                                 
PSEdition                      Desktop                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.14393.1480                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1    
```

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by positivism1**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**
Fixes #121

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/126)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thank you very much @positivism1 for submitting this! It is greatly appreciated and a really awesome job. Review comments and changes are completely normal and expected part of the process :cake: We all get them (any of the people who have reviewed my code will agree :wink: ). Keep up the awesome work!

If you make the changes below and just push back to your branch then hit the Reviewable button on your PR you will be able to click Done on any of the changes you've made and I can continue the review.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzA_G9W6cRGsK3OxNNB:-KzA_G9XgxZTxcCYbfnR:bxmd5t1) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/CHANGELOG.md#L11)):*
> ```Markdown
> - xDiskAccessPath:
>   - Added support for Guid Disk Id type - See [Issue 104](https://github.com/PowerShell/xStorage/issues/104).
>   - Added check for PSDrive existance  to solve bug - See [Issue 121](https://github.com/PowerShell/xStorage/issues/121).
> ```

Please remove extra space between `existance` and `to`.

Also `existance` should be spelled `existence`. :grin:  

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 532 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzA_bDNkbMd2YnuEg7v:-KzA_bDNkbMd2YnuEg7w:b-iowmg5) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L532)):*
> ```PowerShell
>     )
> 
>   Try 
> ```

I think this code actually needs to be moved into the `Set-TargetResource` rather than in `Test-TargetResource`. You'd want to add it just after the volume has been formatted. The reason is that the first time `Test-TargetResource` is hit and the disk isn't already assigned then Get-PSDrive will fire twice and then `Set-TargetResource` will create the new drive. But `Get-PSDrive` needs to fire after the drive has been created but before you try and use it in one of your following steps.

So, I reckon this code needs to go in somewhere around here:
https://github.com/PowerShell/xStorage/blob/dev/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L466

Convert to lower case `T` in `Try`.

Also, the alignment seems a bit off on this code block and there are a few extra spaces at the end of these lines.

The easiest way to fix it is to use Visual Studio Code format document feature. I wrote a quick blog post showing how to use it:
https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 534 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAlR-icMRNjQlA9U4B:-KzAlR-icMRNjQlA9U4C:bgkuggl) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L534)):*
> ```PowerShell
>   Try 
>     {
>           $AccessPathDisk = $AccessPath.split(":")[0]
> ```

Please use lower case for first letter of local variables. E.g.
```powershell
$AccessPathDisk = $AccessPath.split(":")[0]
```

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 539 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAms1ZRfQaNTodHAFG:-KzAms1ZRfQaNTodHAFH:bwjtrj7) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L539)):*
> ```PowerShell
>             $($localizedData.TestingPSDriveMessage -f $AccessPathDisk,$AccessPath)
>         ) -join '' )
>          $TestDrive = Get-PSDrive $AccessPathDisk -ErrorAction Stop
> ```

You could assign this to $null because the result will never be used. Visual Studio Code will underline this as a recommendation :grin:

E.g.
```powershell
$null = Get-PSDrive $AccessPathDisk -ErrorAction Stop
```

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 541 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmj24INx67yQCRxCj:-KzAmj25r7tHoHk2tVRA:be7w4sa) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L541)):*
> ```PowerShell
>          $TestDrive = Get-PSDrive $AccessPathDisk -ErrorAction Stop
>     }
>     Catch
> ```

Please use lower case `C` in `catch`.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 550 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAl6Cw0h1MRuhpRQ1n:-KzAl6Cw0h1MRuhpRQ1o:blh4cap) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L550)):*
> ```PowerShell
> 
>    
>         Get-PSDrive | out-null
> ```

Assigning to $null is faster in older versions of PS (5.1 and below) rather than piping, so can you change to:
```powershell
$null = Get-PSDrive
```

Also, how come this second `Get-PSDrive` is needed? The one above should be hit everytime.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmYIf6xFvwKPMQcxa:-KzAmYIf6xFvwKPMQcxb:bm7li4c) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1#L1)):*
> ```PowerShell
> 
> ```

Can you remove this extra blank line at the top here?

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmaOJkxVOicwhouoy:-KzAmaOKyxnN5B6RUerW:b2rcwhn) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1#L37)):*
> ```PowerShell
>     TestingPSDriveMessage = Testing for availability of PSDrive {0} for AccessPath {1}
>     UnavailablePSDriveMessage = PSDrive {0} is unavailable for AccessPath {1}, refreshing PSDrives.
>   
> ```

Can you remove this extra blank line here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/126#-:-KzAoPPpSi611nFi7tAr:b-rcgj7a)*

**Comment by positivism1** [comment]
Thank you! this is great, I will get to it as soon as I can. From what I remember from my testing, I put the change into Test-TargetResource because that is where the whole thing falls in a heap, when the test-path runs, it can't find the folder because psdrive need refreshing.

**Comment by positivism1** [comment]
Getting back into this now. Apologies, have been away.

**Comment by positivism1** [comment]
The psdrive refresh is in the Test-TargetResource because this is where the error occurs.

This code:
`    Get-PSDrive | out-null`

Is the thing that does the work, only if this line errors..
`$TestDrive = Get-PSDrive $AccessPathDisk -ErrorAction Stop`

Without get-psdrive in catch block (error):
PowerShell DSC resource MSFT_xDiskAccessPath  failed to execute **Test-TargetResource** functionality with error message: Access Path 'E:\DATA' is not found.
Parameter name: AccessPath 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure

With get-psdrive catch block (successful):
VERBOSE: [GDVRATST054]:                            [[xDiskAccessPath]dataAccessPath] Test-TargetResource: Testing disk with Number '2' status for access path 'E:\DATA'.
VERBOSE: [GDVRATST054]:                            [[xDiskAccessPath]dataAccessPath] Test-TargetResource: Testing for availability of PSDrive E for AccessPath E:\DATA
VERBOSE: [GDVRATST054]:                            [[xDiskAccessPath]dataAccessPath] Test-TargetResource: PSDrive E is unavailable for AccessPath E:\DATA, refreshing PSDrives.

Thanks, I will review the code, make changes and set it to Reviewable.

**Comment by PlagueHO** [comment]
Hi @positivism1 - it looks like you've got some merge conflicts that need to be fixed. These will have been caused when another PR got merged before yours. If you can go into Reviewable and click Done on any changes you've completed and the click Publish that will allow me to acknowledge any required changes. Thanks again for your hard word!

**Comment by positivism1** [comment]
ahh yep ok thanks :-) I will try get this Publish button to work.

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzA_G9W6cRGsK3OxNNB:-L02D_1Lp7L1KJIJAgNO:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/CHANGELOG.md#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please remove extra space between `existance` and `to`.

Also `existance` should be spelled `existence`. :grin:  
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 532 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzA_bDNkbMd2YnuEg7v:-L02B-ipWllhCVKUEGx3:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L532)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this code actually needs to be moved into the `Set-TargetResource` rather than in `Test-TargetResource`. You'd want to add it just after the volume has been formatted. The reason is that the first time `Test-TargetResource` is hit and the disk isn't already assigned then Get-PSDrive will fire twice and then `Set-TargetResource` will create the new drive. But `Get-PSDrive` needs to fire after the drive has been created but before you try and use it in one of your following steps.

So, I reckon this code needs to go in somewhere around here:
https://github.com/PowerShell/xStorage/blob/dev/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L466

Convert to lower case `T` in `Try`.

Also, the alignment seems a bit off on this code block and there are a few extra spaces at the end of these lines.

The easiest way to fix it is to use Visual Studio Code format document feature. I wrote a quick blog post showing how to use it:
https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/

</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 534 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAlR-icMRNjQlA9U4B:-L02BFMn4y-u2zE92zJb:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L534)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please use lower case for first letter of local variables. E.g.
```powershell
$AccessPathDisk = $AccessPath.split(":")[0]
```
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 539 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAms1ZRfQaNTodHAFG:-L02B3PiQEIErhe6c0ZB:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L539)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

You could assign this to $null because the result will never be used. Visual Studio Code will underline this as a recommendation :grin:

E.g.
```powershell
$null = Get-PSDrive $AccessPathDisk -ErrorAction Stop
```
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 541 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmj24INx67yQCRxCj:-L02B4AoCejg_hy9OrK5:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L541)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please use lower case `C` in `catch`.
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1, line 550 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAl6Cw0h1MRuhpRQ1n:-L02B0S4nmNhQ9zbp-8K:b-o2ypxi) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.psm1#L550)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Assigning to $null is faster in older versions of PS (5.1 and below) rather than piping, so can you change to:
```powershell
$null = Get-PSDrive
```

Also, how come this second `Get-PSDrive` is needed? The one above should be hit everytime.
</blockquote></details>

This is the one that refreshes the psdrives, the one above tests if the drives are updated or not.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmYIf6xFvwKPMQcxa:-L02BGZqZO3nu2z1AvZR:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this extra blank line at the top here?
</blockquote></details>

Done.

---

*[Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xstorage/126#-KzAmaOJkxVOicwhouoy:-L02BHVhOL1DcWWdUTgc:b-896fix) ([raw file](https://github.com/powershell/xstorage/blob/f60507940b28b768ffb1bf8d671ad3a10b3f275f/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/en-us/MSFT_xDiskAccessPath.strings.psd1#L37)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this extra blank line here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/126#-:-L0D0Yymc4svZZv6qSPu:b-qrmslu)*

**Comment by PlagueHO** [comment]
Hi @positivism1 - are you able to resolve the merge conflicts on this one? I merged another PR in which caused the conflicts.

**Comment by positivism1** [comment]
Yes, would love to, but not exactly sure how. do I need to start again and do a new pull request? or do I manually somehow merge the changes?

**Comment by PlagueHO** [comment]
HI @positivism1 - merge conflicts are super common and easy to fix. What you need to do is rebase your branch with the upstream dev branch. Take a look at these instructions: https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

Basically you'll bring the changes I've made to the upstream Dev branch into your branch, correct any merge conflicts and then push the changes back in. No need to create a new PR or anything.

The challenge will be in your case I had made a non-trivial change to xDiskAccess path to fix a long standing bug so you'll need to figure out how to merge your changes into mine. This hopefully is very straight forward - but if not, tag me and I'll see if I can help point you in the right direction.

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by PlagueHO** [comment]
Superceded by #209

**Pull request closed without merging**
