### PR TITLE
New resources StoragePool and VirtualDisk. Changed xDisk to use for a SP VirtualDisk - Fixes #39

### LINKED ISSUE #39: Create striped volume with multiple disks
There should be a way to add multiple disks to a new volume.

### PR DESCRIPTION
**Pull request by peppekerstens**
Resource StoragePool - create a basic StoragePool
functionality:
Create/(complete)Destroy
Add a disk to existing
Rename a existing
see examples in resources
tested on W2008R2, W2012R2 and Windows 2016

Resource VirtualDisk - create a VirtualDisk
functionality:
Create/(complete)Destroy
see examples in resources
tested on W2008R2, W2012R2 and Windows 2016

Resource cDisk 
added DiskFriendlyName parameter to accommodate for creating disks on a VirtualDisk
added OS detection; will give a nice error on W2008 platform

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xstorage/62)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@peppekerstens - awesome work and some fantastic additions to xStorage - really excited to have access to these resources!

Are you able to run through the [HQRM Module Guidelines](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md) and make sure the changes and new resources meet them?

Just a couple things that I noticed that you'll want to resolve (aside from the HQRM stuff) before getting a full review:
- The resource folders and filenames names should be MSFT_x*
- Unit tests should be included as well as Integration tests (where possible) - they should also be based on the standard [tests templates](https://github.com/PowerShell/DscResources/tree/master/Tests.Template).

Also, one heads up, I have [another PR](https://github.com/PowerShell/xStorage/pull/60) going through for this module that brings all the existing resources up to HQRM, which may cause merge conflicts in this PR (or vice versa).

**Comment by peppekerstens** [comment]
@PlagueHO - yes I noticed. I propose to have your PR made final first. I will pick-up from that and re-write this one. Makes most sense... Just wanted to 'pitch-in and share'.  I propose to leave this on-line for now so people are able to use the code if need-be.

2 things;
1. I have little to none practical knowledge with pester. I am hoping someone can help with that. (when I've re-written?)
2. I am a little confused about the x-thing. Even the HQRM Module Guidelines mention it should be dropped; there's no logical reason to keep up the 'COMPANY_x' and 'COMPANY_c' naming convention as we're all using GitHub/powershellgallery now. But...if you're certain that no review will take place without this naming; I will gladly rename.

**Comment by PlagueHO** [comment]
Hi @peppekerstens - not sure when my PR will go through - the Microsoft DSC team are super busy and have so many reviews to get through it can take time.

1. But your PR is awesome and definitely provide some awesome features. I'm happy to help you out with the Pester tests for sure. Once my PR has gone through I'll be able to look at your PR and advise on the unit and integration tests. If you're interested I wrote a blog series on it.

2. Just call the resources 'xAAAAAA' (or 'MSFT_xAAAAAA') for now. Once the whole resource module meets the minimum standards for HQRM then it might be allowed to be converted to the new AAAAAAAADsc naming format.

The 'cAAAAAAA' is only used for complete DSC resource modules that are maintained outside the Microsoft DSC Resource Kit. Once your resources are accepted into this resource module they are  become part of the Microsoft DSC Resource Kit so must be named 'x' (unless they get converted to HQRM).

Anyway, really appreciate your contributions! They are awesome features!

**Comment by joshan1120** [comment]
This does not work for me in my testing. If I supply a value for "Size" it errors every time. I do not want to use max size so I need to specify a size.

PowerShell DSC resource VirtualDisk  failed to execute Set-TargetResource functionality with error message: VirtualDisk Set-TargetResource failed with the following error: 'Cannot process argument transformation on parameter 'Size'. Cannot 
convert value "10*1073741824" to type "System.UInt64". Error: "Input string was not in a correct format."' 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Here is the resource

VirtualDisk test {
					FriendlyName = "test"
					StoragePoolFriendlyName = "test"
					Size = 10

**Comment by joshan1120** [comment]
ok, I will lead by saying I am very new to DSC and not a powershell expert. However, I made the following changes and the VirtualDisk resource now works for me.

1. I changed the param from an integer to a string.
2. I remove all of the math from all instances of $Size
3. I changed the Size attribute of the resource as shown below

VirtualDisk test {
					FriendlyName = "test"
					StoragePoolFriendlyName = "MS-SQL-Drives"
					Size = 10GB

It now created virtual disks as expected.

**Comment by PlagueHO** [comment]
Hi @peppekerstens - I've started to review this resource, but the ITON_cDisk resource seems to duplicate functionality in the MSFT_xDisk. Should this resource be included in this PR?

These resources look really great and will be awesome additions to this module.

We will need to get a few things added though to meet the DSC Resource kit [contribution guidelines](https://github.com/PlagueHO/DscResources/blob/master/CONTRIBUTING.md):
1. [Unit tests](https://github.com/PlagueHO/DscResources/blob/master/CONTRIBUTING.md#write-tests)
2. [Integration tests (where possible)](https://github.com/PlagueHO/DscResources/blob/master/CONTRIBUTING.md#write-tests)
3. Add the details to the Readme.md based on [this template](https://github.com/PlagueHO/DscResources/blob/master/DscResource.Template/README.md).
4. Update the [release notes](https://github.com/PlagueHO/DscResources/blob/master/CONTRIBUTING.md#update-the-release-notes)

If you're not familiar with Pester tests, I can give you some great stuff to get you started. I'm also happy to help you out creating them (although I'm a bit short on time at the moment so it might take me a while to get to them).

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xstorage/62#-:-KWWa7ly_ZL9_-IGPaob:b-yf3lbc)*

**Comment by willusher** [comment]
Hi @peppekerstens - Thanks for this code. I was about to start writing this myself until I found your code. I rebased your commit on HEAD and (aside from a couple minor bugfixes) was able to use it to configure a moderately complex disk configuration across a bunch of servers.

I'd really like to see this merged, and I've got some time I can allocate to helping. You haven't engaged in a month, so I'm not sure if you're still interested in making all the changes needed to meet the contribution guidelines, or if you'd like me to take over from here? 

I'm happy to send you my fixes so you can add them to your PR. Let me know how you'd like to proceed. Thanks.

**Comment by PlagueHO** [comment]
Hi @willusher  - it does look like @peppekerstens may have forgotten this PR. So if you're happy to take over the PR then that would be awesome!!!!

**Comment by willusher** [comment]
Hi @PlagueHO - Just wanted to let you know that I haven't forgotten this. There's a somewhat slow process to get an open source project approved for contribution within my company, but I'm working through that right now and hope to have a PR open soon.

**Comment by PlagueHO** [comment]
No worries @peppekerstens - I'll keep the PR open :grin:

**Comment by PlagueHO** [comment]
Hi @willusher - is this one still active? No worries if it is - just wanted to check!

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by PlagueHO** [comment]
I'm going to close this one for now. It can be reopened if someone wants to work on it.

**Pull request closed without merging**
