### PR TITLE
Disk: correct volume error -  drive is read only

### LINKED ISSUE #85: xStorage - Cannot perform the requested operation when the drive is read only
When attempting to use 2.9.0.0 I keep getting volumes left in a "raw" volumes with assigned driver letters state even when specifying FSFormat. In the logs I am getting the following errors:

VERBOSE: [localhost]:                            [[xDisk]Edrive_xDISK] Set-TargetResource: Creat
ing partition on disk number '2' with drive letter 'E' using all free space.
VERBOSE: [localhost]:                            [[xDisk]Edrive_xDISK] Set-TargetResource: Forma
tting the volume as 'NTFS'.
Cannot perform the requested operation when the drive is read only
    + CategoryInfo          : NotSpecified: (StorageWMI:) [], CimException
    + FullyQualifiedErrorId : StorageWMI 43006,Format-Volume
    + PSComputerName        : localhost
 
VERBOSE: [ocalhost]: LCM:  [ End    Set      ]  [[xDisk]Edrive_xDISK]  in 2.4240 seconds.
The PowerShell DSC resource '[xDisk]Edrive_xDISK' with SourceInfo 
'C:\Users\myprofile\Desktop\TestDSC\SSRSDSC.ps1::71::9::xDisk' threw one or more non-terminating 
errors while running the Set-TargetResource functionality. These errors are logged to the ETW 
channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

Below is an example of the config I am using when getting this error:

        xDisk Hdrive_xDISK
        {
             DiskNumber = 5
             DriveLetter = "H"
             FSlabel = "TempDB"
             FSFormat = "NTFS"
             AllocationUnitSize = 65536
             DependsOn = "[xWaitforDisk]Disk5_xDISK"
        }

I can say that if I keep going back and deleting the volume and running the dsc config it will eventually get a correct NTFS volume, but takes about 3 to 5 times before it won't be in a broken state with a "raw" volume. I have also looked at the disk and confirm they are not in read only. Assuming something in the dsc resource is temporarily putting the disk into a read only mode, but as soon as the config is complete and bombs out the disk is not in read only mode. 

If I drop back down to my previous version I was using successfully (2.6.0.0), this problem does not exist.

### PR DESCRIPTION
**Pull request by JoshuaJSwain**
#### Task list

- [X ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/183)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Closing and Reopening PR to trigger CLA check.

**Comment by PlagueHO** [comment]
Hi @JoshuaJSwain - It looks like the tests (unit and integration) are failing on this. Are you able to look into these?

**Comment by PlagueHO** [comment]
@JoshuaJSwain - are there any other methods of detecting if the disk/partition/volume is readonly rather than just retrying the format? Just think it might be worth checking this.

**Comment by JoshuaJSwain** [comment]
I can't seem to find any identifying properties of the partition being not ready that can be tested against in powershell. I'll need help with the unit tests as I'm not sure why those are failing. 


Import-Module 'C:\Program Files\WindowsPowerShell\Modules\StorageDsc\Modules\StorageDsc\DSCResources\MSFTDSC_Disk\MSFTDSC_Disk.psm1'

Set-TargetResource -DriveLetter z -FSLabel test -AllocationUnitSize 65536 -FSFormat NTFS -PartitionStyle GPT -DiskIdType UniqueId -DiskId 6000C2921F16E654D83EE153F15DB810 -Verbose
VERBOSE: Set-TargetResource: Setting disk with UniqueId '6000C2921F16E654D83EE153F15DB810' status for drive letter 'z'.
VERBOSE: Set-TargetResource: Checking disk with UniqueId '6000C2921F16E654D83EE153F15DB810' partition style.
VERBOSE: Set-TargetResource: Disk with UniqueId '6000C2921F16E654D83EE153F15DB810' is already initialized with 'GPT'.
VERBOSE: Set-TargetResource: Disk with UniqueId '6000C2921F16E654D83EE153F15DB810' does not contain a partition assigned to drive letter 'z'.
VERBOSE: Set-TargetResource: Creating partition on disk with UniqueId '6000C2921F16E654D83EE153F15DB810' with drive letter 'z' using all free space.
VERBOSE: Set-TargetResource: Formatting the volume as 'NTFS'.
Format-Volume : Cannot perform the requested operation when the drive is read only
At C:\Program Files\WindowsPowerShell\Modules\StorageDsc\Modules\StorageDsc\DSCResources\MSFTDSC_Disk\MSFTDSC_Disk.psm1:570 char:32
+     $volume = $partition | Format-Volume @VolParams
+                                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimException
    + FullyQualifiedErrorId : StorageWMI 43006,Format-Volume


reproduce outside the module attempting to get any information from the partition to test against for this race condition:

Get-Disk -UniqueId 6000C2921F16E654D83EE153F15DB810 | get-Partition | Remove-Partition -Confirm:$false
$disk = Get-Disk -UniqueId 6000C2921F16E654D83EE153F15DB810
$partition = $disk | New-Partition -UseMaximumSize
$partition = $partition | Get-Partition
$volume = $partition | Get-Volume
$volume = $partition | Format-Volume -FileSystem NTFS -NewFileSystemLabel test -AllocationUnitSize 65536 -Confirm:$false
Format-Volume : Cannot perform the requested operation when the drive is read only
At line:6 char:24
+ ... partition | Format-Volume -FileSystem NTFS -NewFileSystemLabel test - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimException
    + FullyQualifiedErrorId : StorageWMI 43006,Format-Volume

$partition | format-custom *

class CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_Partition
{
  OperationalStatus = Online
  Type = Basic
  AccessPaths = 
    [
      \\?\Volume{7cc54cbc-0131-442d-923f-bae14ff12c0f}\
    ]
    
  DiskId = \\?\scsi#disk&ven_vmware&prod_virtual_disk#5&4a84755&0&000800#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
  DiskNumber = 7
  DriveLetter =  
  GptType = {ebd0a0a2-b9e5-4433-87c0-68b6b72699c7}
  Guid = {7cc54cbc-0131-442d-923f-bae14ff12c0f}
  IsActive = False
  IsBoot = False
  IsHidden = False
  IsOffline = False
  IsReadOnly = False
  IsShadowCopy = False
  IsSystem = False
  MbrType = 
  NoDefaultDriveLetter = True
  Offset = 1048576
  PartitionNumber = 1
  Size = 9661579264
  TransitionState = 1
  PSComputerName = 
  CimClass = 
    class CimClass
    {
      CimSuperClassName = 
      CimSuperClass = 
      CimClassProperties = 
        [
          class CimClassPropertyOfClass
          {
            Name = AccessPaths
            Value = 
            CimType = StringArray
            Flags = Property, ReadOnly, NullValue
            Qualifiers = 
              [
                class CimQualifierOfProperty
                {
                  Name = read
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
            ReferenceClassName = 
          }
          class CimClassPropertyOfClass
          {
            Name = DiskId
            Value = 
            CimType = String
            Flags = Property, Key, ReadOnly, NullValue
            Qualifiers = 
              [
                class CimQualifierOfProperty
                {
                  Name = key
                  Value = True
                  CimType = Boolean
                  Flags = DisableOverride, ToSubclass
                }
                class CimQualifierOfProperty
                {
                  Name = ModelCorrespondence
                  Value = 
                    [
                      MSFT_Disk.ObjectId
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
                class CimQualifierOfProperty
                {
                  Name = read
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
            ReferenceClassName = 
          }
          class CimClassPropertyOfClass
          {
            Name = DiskNumber
            Value = 
            CimType = UInt32
            Flags = Property, Required, ReadOnly, NullValue
            Qualifiers = 
              [
                class CimQualifierOfProperty
                {
                  Name = ModelCorrespondence
                  Value = 
                    [
                      MSFT_Disk.Number
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
                class CimQualifierOfProperty
                {
                  Name = read
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, ToSubclass
                }
                class CimQualifierOfProperty
                {
                  Name = Required
                  Value = True
                  CimType = Boolean
                  Flags = DisableOverride, ToSubclass
                }
              ]
              
            ReferenceClassName = 
          }
          class CimClassPropertyOfClass
          {
            Name = DriveLetter
            Value = 
            CimType = Char16
            Flags = Property, ReadOnly, NullValue
            Qualifiers = 
              [
                class CimQualifierOfProperty
                {
                  Name = read
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
            ReferenceClassName = 
          }
          ...
        ]
        
      CimClassQualifiers = 
        [
          class CimQualifierOfClass
          {
            Name = dynamic
            Value = True
            CimType = Boolean
            Flags = EnableOverride, ToSubclass
          }
          class CimQualifierOfClass
          {
            Name = locale
            Value = 1033
            CimType = SInt32
            Flags = EnableOverride, Restricted
          }
          class CimQualifierOfClass
          {
            Name = provider
            Value = StorageWMI
            CimType = String
            Flags = EnableOverride, ToSubclass
          }
        ]
        
      CimClassMethods = 
        [
          class CimMethodDeclarationOfClass
          {
            Name = DeleteObject
            ReturnType = UInt32
            Parameters = 
              [
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = ExtendedStatus
                  CimType = Instance
                  Qualifiers = 
                    [
                      EmbeddedInstance = "MSFT_StorageExtendedStatus"
                      ID = 0
                      Out = True
                    ]
                    
                  ReferenceClassName = 
                }
              ]
              
            Qualifiers = 
              [
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = implemented
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, Restricted
                }
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = Required
                  Value = True
                  CimType = Boolean
                  Flags = DisableOverride, ToSubclass
                }
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = ValueMap
                  Value = 
                    [
                      0
                      1
                      2
                      3
                      ...
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
          }
          class CimMethodDeclarationOfClass
          {
            Name = GetAccessPaths
            ReturnType = UInt32
            Parameters = 
              [
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = AccessPaths
                  CimType = StringArray
                  Qualifiers = 
                    [
                      ID = 0
                      Out = True
                    ]
                    
                  ReferenceClassName = 
                }
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = ExtendedStatus
                  CimType = Instance
                  Qualifiers = 
                    [
                      EmbeddedInstance = "MSFT_StorageExtendedStatus"
                      ID = 1
                      Out = True
                    ]
                    
                  ReferenceClassName = 
                }
              ]
              
            Qualifiers = 
              [
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = implemented
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, Restricted
                }
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = ValueMap
                  Value = 
                    [
                      0
                      1
                      2
                      3
                      ...
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
          }
          class CimMethodDeclarationOfClass
          {
            Name = AddAccessPath
            ReturnType = UInt32
            Parameters = 
              [
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = AccessPath
                  CimType = String
                  Qualifiers = 
                    [
                      ID = 0
                      In = True
                    ]
                    
                  ReferenceClassName = 
                }
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = AssignDriveLetter
                  CimType = Boolean
                  Qualifiers = 
                    [
                      ID = 1
                      In = True
                    ]
                    
                  ReferenceClassName = 
                }
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = ExtendedStatus
                  CimType = Instance
                  Qualifiers = 
                    [
                      EmbeddedInstance = "MSFT_StorageExtendedStatus"
                      ID = 2
                      Out = True
                    ]
                    
                  ReferenceClassName = 
                }
              ]
              
            Qualifiers = 
              [
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = implemented
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, Restricted
                }
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = ValueMap
                  Value = 
                    [
                      0
                      1
                      2
                      3
                      ...
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
          }
          class CimMethodDeclarationOfClass
          {
            Name = RemoveAccessPath
            ReturnType = UInt32
            Parameters = 
              [
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = AccessPath
                  CimType = String
                  Qualifiers = 
                    [
                      ID = 0
                      In = True
                      Required = True
                    ]
                    
                  ReferenceClassName = 
                }
                class CimMethodParameterDeclarationOfMethod
                {
                  Name = ExtendedStatus
                  CimType = Instance
                  Qualifiers = 
                    [
                      EmbeddedInstance = "MSFT_StorageExtendedStatus"
                      ID = 1
                      Out = True
                    ]
                    
                  ReferenceClassName = 
                }
              ]
              
            Qualifiers = 
              [
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = implemented
                  Value = True
                  CimType = Boolean
                  Flags = EnableOverride, Restricted
                }
                class CimMethodQualifierDeclarationOfMethod
                {
                  Name = ValueMap
                  Value = 
                    [
                      0
                      1
                      2
                      3
                      ...
                    ]
                    
                  CimType = StringArray
                  Flags = EnableOverride, ToSubclass
                }
              ]
              
          }
          ...
        ]
        
      CimSystemProperties = 
        class CimSystemProperties
        {
          Namespace = ROOT/Microsoft/Windows/Storage
          ServerName = BO1DEMO01
          ClassName = MSFT_Partition
          Path = 
        }
      CimClassName = MSFT_Partition
    }
  CimInstanceProperties = 
    [
      class CimPropertyOfInstance
      {
        Name = AccessPaths
        Value = 
          [
            \\?\Volume{7cc54cbc-0131-442d-923f-bae14ff12c0f}\
          ]
          
        CimType = StringArray
        Flags = Property, ReadOnly, NotModified
        IsValueModified = False
      }
      class CimPropertyOfInstance
      {
        Name = DiskId
        Value = \\?\scsi#disk&ven_vmware&prod_virtual_disk#5&4a84755&0&000800#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
        CimType = String
        Flags = Property, Key, ReadOnly, NotModified
        IsValueModified = False
      }
      class CimPropertyOfInstance
      {
        Name = DiskNumber
        Value = 7
        CimType = UInt32
        Flags = Property, Required, ReadOnly, NotModified
        IsValueModified = False
      }
      class CimPropertyOfInstance
      {
        Name = DriveLetter
        Value =  
        CimType = Char16
        Flags = Property, ReadOnly, NotModified
        IsValueModified = False
      }
      ...
    ]
    
  CimSystemProperties = 
    class CimSystemProperties
    {
      Namespace = ROOT/Microsoft/Windows/Storage
      ServerName = BO1DEMO01
      ClassName = MSFT_Partition
      Path = 
    }
}

**Comment by JoshuaJSwain** [comment]
@PlagueHO I did some more testing and we can simplify the fix by adding the sleep wait right after the new-partition creation to avoid the race condition.

**Comment by PlagueHO** [comment]
Cool! Thanks @JoshuaJSwain - I'll complete the review tomorrow! Just got a couple of other reviews to get through tonight.

**Comment by PlagueHO** [comment]
Hi @JoshuaJSwain - On it now! :grin: sorry about the delay!

**Comment by JoshuaJSwain** [comment]
Hi @plagueho checking for feedback on this one.

**Comment by PlagueHO** [comment]
On it tonight- sorry about the delay again!

**Comment by PlagueHO** [comment]
@JoshuaJSwain - I messed up and didn't notice you'd raised your PR against the Master branch. So I've got to revert it. Can you re-raise this PR against the Dev branch again for me and I'll get it through quickly.

**Pull request merged**
