### PR TITLE
DiskAccessPath: Access Path not found - Fixes #121

### LINKED ISSUE #121: xDiskAccessPath fails test for disk and accesspath after disk format and folder creation.
**xDiskAccessPath:**
xDiskAccessPath fails the disk and access path test when the Disk and Folder are created within the same configuration.
```

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager
,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer TESTAPI with user sid S-1-5-21-1463861888-1148693830-2432142812-152739.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Testing disk with Number '1' status for drive letter 'E'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Checking if disk with Number '1' is initialized.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Test-TargetResource: Disk with Number '1' is initialized with 'RAW' partition style. GPT required
.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[xDisk]Disk1]  in 2.3400 seconds.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Setting disk with Number '1' status for drive letter 'E'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Checking disk with Number '1' partition style.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Initializing disk with Number '1'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Disk with Number '1' does not contain a partition assigned to drive letter 'E
'.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Creating partition on disk with Number '1' with drive letter 'E' using all fr
ee space.
VERBOSE: [TESTAPI]:                            [[xDisk]Disk1] Set-TargetResource: Formatting the volume as 'NTFS'.
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]  [[xDisk]Disk1]  in 3.6750 seconds.
VERBOSE: [TESTAPI]: LCM:  [ End    Resource ]  [[xDisk]Disk1]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The system cannot find the file specified.
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The related file/directory is: E:\DATA.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[File]createDataFolder]  in 0.0320 seconds.
VERBOSE: [TESTAPI]: LCM:  [ Start  Set      ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The system cannot find the file specified.
VERBOSE: [TESTAPI]:                            [[File]createDataFolder] The related file/directory is: E:\DATA.
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]  [[File]createDataFolder]  in 0.0150 seconds.
VERBOSE: [TESTAPI]: LCM:  [ End    Resource ]  [[File]createDataFolder]
VERBOSE: [TESTAPI]: LCM:  [ Start  Resource ]  [[xDiskAccessPath]dataAccessPath]
VERBOSE: [TESTAPI]: LCM:  [ Start  Test     ]  [[xDiskAccessPath]dataAccessPath]
VERBOSE: [TESTAPI]:                            [[xDiskAccessPath]dataAccessPath] Test-TargetResource: Testing disk with Number '2' status for access path 'E:\D
ATA\'.
VERBOSE: [TESTAPI]: LCM:  [ End    Test     ]  [[xDiskAccessPath]dataAccessPath]  in 0.1250 seconds.
PowerShell DSC resource MSFT_xDiskAccessPath  failed to execute Test-TargetResource functionality with error message: Access Path 'E:\DATA\' is not found.
Parameter name: AccessPath 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : TestAPI
 
VERBOSE: [TESTAPI]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : TestAPI
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 6.399 seconds


```**The DSC configuration that is using the resource (as detailed as possible):**
```
  Configuration AccessPath
  {
  
      Import-DscResource -ModuleName "xStorage"

  Node 'TestAPI' {
        
            xDisk Disk1{
              DiskID = "1"
              DriveLetter = 'E'
              FSLabel = "TestAPI_E"
              FSFormat="NTFS"
              }

              File createDataFolder{
              Type = 'Directory'
              DestinationPath = "E:\DATA\"
              Ensure = 'Present'
              DependsOn = "[xDisk]Disk1"
              }
             xDiskAccessPath dataAccessPath{
              DiskID=2
              AccessPath="E:\DATA\"
              Size = 5GB
              FSLabel = "E_DATA"
              FSFormat = 'NTFS'
              }
    }
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Microsoft Windows Server 2016 Standard
```
Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.1.14393.1480                                                                                                                 
PSEdition                      Desktop                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.14393.1480                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1    
```

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by tcotten**
**Pull Request (PR) description**
Added PSDrive logic to fix an issue when doing a chain of events: creating a disk, adding a folder and then creating a mount point against it.

**This Pull Request (PR) fixes the following issues:**
Fixes #121 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/152)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thank you very much @tcotten for picking this up - it is much appreciated!

Is it possible to extend the unit tests as well to cover the new lines here as the code coverage has gone down.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 197 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIyUGQDo8zGfGIr6KR:-LEIyUGQDo8zGfGIr6KS:b9jyoh6) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L197)):*
> ```PowerShell
>         ) -join '' )
> 
>     # Validate that the PSDrive is available
> ```

Could you possibly extend this comment to mention why this is needed? 

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 198 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIwPsd88BE7DJRLeiB:-LEIwPsd88BE7DJRLeiC:b7tnmdz) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L198)):*
> ```PowerShell
> 
>     # Validate that the PSDrive is available
>     Try
> ```

Can you change this to lower case t - e.g. `try`?

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 200 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIxE6V2VE5XSIkaWXc:-LEIxE6V2VE5XSIkaWXd:b-a58dxg) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L200)):*
> ```PowerShell
>     Try
>     {
>         $accessPathDisk = $AccessPath.Split(":")[0]
> ```

Can you change the double quotes to single quotes here?

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 205 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIwZ2sD2YtAD3-OaM-:-LEIwZ2sD2YtAD3-OaM0:b-d9mjjq) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L205)):*
> ```PowerShell
>                 $($localizedData.CheckingPSDriveMessage -f $accessPathDisk, $AccessPath)
>             ) -join '' )
>         Get-PSDrive $accessPathDisk -ErrorAction Stop
> ```

Can you use named parameter here? E.g.
```powershell
Get-PSDrive -Name $accessPathDisk -ErrorAction Stop
```

You'll also want to assign this to $null to dump the result e.g.
```powershell
$null = Get-PSDrive -Name $accessPathDisk -ErrorAction Stop
```

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 207 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIwUOJ1cZCenA27XMN:-LEIwUOJ1cZCenA27XMO:b-9gvby2) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L207)):*
> ```PowerShell
>         Get-PSDrive $accessPathDisk -ErrorAction Stop
>     }
>     Catch
> ```

Can you change this to lower case c - e.g. `catch`?

---

*[Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1, line 214 at r1](https://reviewable.io/reviews/powershell/storagedsc/152#-LEIx_EB6ad9Sha8BJge:-LEIx_EB6ad9Sha8BJgf:b-9bwqap) ([raw file](https://github.com/powershell/storagedsc/blob/a55660b2aa0074e4d62c6f0d39009949e4fc2f9d/Modules/StorageDsc/DSCResources/MSFT_DiskAccessPath/MSFT_DiskAccessPath.psm1#L214)):*
> ```PowerShell
>             ) -join '' )
> 
>         Get-PSDrive | Out-Null
> ```

For consistency with the out resources in this module could you assign this to $null rather than pass it in the pipeline?

E.g.
```powershell
$null = Get-PSDrive
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/152#-:-LEIysLp4_X82c591Ze4:bccperd)*

**Comment by tcotten** [comment]
Thanks for the great feedback @PlagueHO. I was working through coming up with some testing around this and found that although the Get-PSDrive may help sometimes, after running many tests it doesn't appear to be a consistent solution. Through the testing I think I found where the issue is and I'm not sure how best to solve it yet.

In the Assert-AccessPathValid function during the Test-TargetResource execution it periodically throws an exception. 
`
if (-not (Test-Path -Path $AccessPath -PathType Container))
    {
        # AccessPath is invalid
        New-InvalidArgumentException `
            -Message $($LocalizedData.InvalidAccessPathError -f $AccessPath) `
            -ArgumentName 'AccessPath'
    } # if
`

Periodic Exception during Test-TargetResource:
>VERBOSE: [Win2016VM01]: LCM:  [ Start  Resource ]  [[DiskAccessPath]dataAccessPath]
>VERBOSE: [Win2016VM01]: LCM:  [ Start  Test     ]  [[DiskAccessPath]dataAccessPath]
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Test-TargetResource: Testing disk with Number '2' status for access path 'F:\DATA\'.
>VERBOSE: [Win2016VM01]: LCM:  [ End    Test     ]  [[DiskAccessPath]dataAccessPath]  in 0.0150 seconds.
>PowerShell DSC resource MSFT_DiskAccessPath  failed to execute Test-TargetResource functionality with error message: **Access Path 'F:\DATA\' is not found.**
>Parameter name: AccessPath 


At this point it doesn't continue. When I change the Assert-AccessPathValid function to just log the exception then it consistently passes the Test-TargetResource (while logging the failure) and moves on to the Set-TargetResource which then succeeds even though this Test-Path fails.

` 
   if (-not (Test-Path -Path $AccessPath -PathType Container))
    {
        Write-Verbose -Message ( @(
                "$($MyInvocation.MyCommand): "
                $($LocalizedData.InvalidAccessPathError -f $AccessPath)
            ) -join '' )
    } # if
`
Output:
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Test-TargetResource: Checking if disk with Number '2' is initialized.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Test-TargetResource: A volume assigned to access path 'F:\DATA\' was not found.
>VERBOSE: [Win2016VM01]: LCM:  [ End    Test     ]  [[DiskAccessPath]dataAccessPath]  in 0.2650 seconds.
>VERBOSE: [Win2016VM01]: LCM:  [ Start  Set      ]  [[DiskAccessPath]dataAccessPath]
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Setting disk with Number '2' status for access path 'F:\DATA\'.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Checking disk with Number '2' partition style.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Disk with Number '2' is already initialized with GPT.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Disk with Number '2' does not contain a partition assigned to access path 'F:\DATA\'.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Disk with Number '2' already contains paritions, but none match required size.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Creating partition on disk with Number '2' using 51200 KB.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Formatting the volume as 'NTFS'.
>VERBOSE: [Win2016VM01]:                            [[DiskAccessPath]dataAccessPath] Set-TargetResource: Successfully initialized volume and assigned to access path 'F:\DATA\'.
>VERBOSE: [Win2016VM01]: LCM:  [ End    Set      ]  [[DiskAccessPath]dataAccessPath]  in 3.9230 seconds.

Let me know if you have any suggestions or thoughts on next steps and I'll see what I can do to make it happen.

**Comment by PlagueHO** [comment]
That is some great info/detecting there @tcotten. It would appear that there is a delay between creation of the folder `F:\Data` in the File resource before it can be accessed by the DiskAccessPath resource. Did you notice that if you applied the config twice, would it pass the second time (assuming you still had the exception in there rather than the `Write-Verbose`)? And it does seem that the call to `Get-PSDrive` doesn't always cause the folder to appear - is that correct?

**Comment by tcotten** [comment]
@PlagueHO - Interestingly, in my testing and re-testing I found that sometimes re-running it would be successful and sometimes it would take a number of retries before it would work which correlates to your thoughts on it being a timing issue related to the File resource creation. You are also correct that the call to Get-PSDrive doesn't always cause the folder to appear. I started trying to track down the File resource to see if I could dig deeper but wasn't able to find it.

Another potential I've been thinking through is perhaps the Folder is actually there on some level and the Test-Path call is failing to detect it at that point after the File resource is complete. The reason I'm thinking this is because when I use the `Write-Verbose` it is always successful in its execution which if it wasn't there or a timing issue I would expect that some percentage of the time it should fail to create the DiskAccessPath resource.

**Comment by PlagueHO** [comment]
Bump

**Comment by PlagueHO** [comment]
I'll pick this up and get it through soon.

**Comment by PlagueHO** [comment]
Superceded by #209

**Pull request closed without merging**
